/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as dashboardLayoutRouteImport } from './routes/(dashboard)/layout'
import { Route as authLayoutRouteImport } from './routes/(auth)/layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as dashboardSettingsLayoutRouteImport } from './routes/(dashboard)/settings/layout'
import { Route as ApiTranscribeIndexRouteImport } from './routes/api/transcribe/index'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as dashboardSettingsIndexRouteImport } from './routes/(dashboard)/settings/index'
import { Route as dashboardOverviewIndexRouteImport } from './routes/(dashboard)/overview/index'
import { Route as dashboardOrganizationsIndexRouteImport } from './routes/(dashboard)/organizations/index'
import { Route as dashboardChatIndexRouteImport } from './routes/(dashboard)/chat/index'
import { Route as authTwoFactorIndexRouteImport } from './routes/(auth)/two-factor/index'
import { Route as ApiStorageSplatRouteImport } from './routes/api/storage/$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiChatResumeRouteImport } from './routes/api/chat/resume'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as dashboardSettingsSecurityRouteImport } from './routes/(dashboard)/settings/security'
import { Route as dashboardSettingsBillingRouteImport } from './routes/(dashboard)/settings/billing'
import { Route as dashboardSettingsAppearanceRouteImport } from './routes/(dashboard)/settings/appearance'
import { Route as authTwoFactorOtpRouteImport } from './routes/(auth)/two-factor/otp'
import { Route as authAcceptInvitationInvitationIdRouteImport } from './routes/(auth)/accept-invitation/$invitationId'
import { Route as dashboardOrganizationsInvitationsIndexRouteImport } from './routes/(dashboard)/organizations/invitations/index'

const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardLayoutRoute = dashboardLayoutRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authLayoutRoute = authLayoutRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authLayoutRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => authLayoutRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authLayoutRoute,
} as any)
const dashboardSettingsLayoutRoute = dashboardSettingsLayoutRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const ApiTranscribeIndexRoute = ApiTranscribeIndexRouteImport.update({
  id: '/api/transcribe/',
  path: '/api/transcribe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsIndexRoute = dashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardSettingsLayoutRoute,
} as any)
const dashboardOverviewIndexRoute = dashboardOverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const dashboardOrganizationsIndexRoute =
  dashboardOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)
const dashboardChatIndexRoute = dashboardChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => dashboardLayoutRoute,
} as any)
const authTwoFactorIndexRoute = authTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => authLayoutRoute,
} as any)
const ApiStorageSplatRoute = ApiStorageSplatRouteImport.update({
  id: '/api/storage/$',
  path: '/api/storage/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatResumeRoute = ApiChatResumeRouteImport.update({
  id: '/api/chat/resume',
  path: '/api/chat/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsSecurityRoute =
  dashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const dashboardSettingsBillingRoute =
  dashboardSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const dashboardSettingsAppearanceRoute =
  dashboardSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => dashboardSettingsLayoutRoute,
  } as any)
const authTwoFactorOtpRoute = authTwoFactorOtpRouteImport.update({
  id: '/two-factor/otp',
  path: '/two-factor/otp',
  getParentRoute: () => authLayoutRoute,
} as any)
const authAcceptInvitationInvitationIdRoute =
  authAcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => authLayoutRoute,
  } as any)
const dashboardOrganizationsInvitationsIndexRoute =
  dashboardOrganizationsInvitationsIndexRouteImport.update({
    id: '/organizations/invitations/',
    path: '/organizations/invitations/',
    getParentRoute: () => dashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/settings': typeof dashboardSettingsLayoutRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/settings/billing': typeof dashboardSettingsBillingRoute
  '/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/two-factor/': typeof authTwoFactorIndexRoute
  '/chat/': typeof dashboardChatIndexRoute
  '/organizations/': typeof dashboardOrganizationsIndexRoute
  '/overview/': typeof dashboardOverviewIndexRoute
  '/settings/': typeof dashboardSettingsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/transcribe/': typeof ApiTranscribeIndexRoute
  '/organizations/invitations/': typeof dashboardOrganizationsInvitationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/two-factor/otp': typeof authTwoFactorOtpRoute
  '/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/settings/billing': typeof dashboardSettingsBillingRoute
  '/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/two-factor': typeof authTwoFactorIndexRoute
  '/chat': typeof dashboardChatIndexRoute
  '/organizations': typeof dashboardOrganizationsIndexRoute
  '/overview': typeof dashboardOverviewIndexRoute
  '/settings': typeof dashboardSettingsIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/transcribe': typeof ApiTranscribeIndexRoute
  '/organizations/invitations': typeof dashboardOrganizationsInvitationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authLayoutRouteWithChildren
  '/(dashboard)': typeof dashboardLayoutRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/(dashboard)/settings': typeof dashboardSettingsLayoutRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/accept-invitation/$invitationId': typeof authAcceptInvitationInvitationIdRoute
  '/(auth)/two-factor/otp': typeof authTwoFactorOtpRoute
  '/(dashboard)/settings/appearance': typeof dashboardSettingsAppearanceRoute
  '/(dashboard)/settings/billing': typeof dashboardSettingsBillingRoute
  '/(dashboard)/settings/security': typeof dashboardSettingsSecurityRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/resume': typeof ApiChatResumeRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/storage/$': typeof ApiStorageSplatRoute
  '/(auth)/two-factor/': typeof authTwoFactorIndexRoute
  '/(dashboard)/chat/': typeof dashboardChatIndexRoute
  '/(dashboard)/organizations/': typeof dashboardOrganizationsIndexRoute
  '/(dashboard)/overview/': typeof dashboardOverviewIndexRoute
  '/(dashboard)/settings/': typeof dashboardSettingsIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/transcribe/': typeof ApiTranscribeIndexRoute
  '/(dashboard)/organizations/invitations/': typeof dashboardOrganizationsInvitationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/themes'
    | '/settings'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/two-factor/otp'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/two-factor/'
    | '/chat/'
    | '/organizations/'
    | '/overview/'
    | '/settings/'
    | '/api/chat/'
    | '/api/transcribe/'
    | '/organizations/invitations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/themes'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/accept-invitation/$invitationId'
    | '/two-factor/otp'
    | '/settings/appearance'
    | '/settings/billing'
    | '/settings/security'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/two-factor'
    | '/chat'
    | '/organizations'
    | '/overview'
    | '/settings'
    | '/api/chat'
    | '/api/transcribe'
    | '/organizations/invitations'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(dashboard)'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/themes'
    | '/(dashboard)/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/accept-invitation/$invitationId'
    | '/(auth)/two-factor/otp'
    | '/(dashboard)/settings/appearance'
    | '/(dashboard)/settings/billing'
    | '/(dashboard)/settings/security'
    | '/api/auth/$'
    | '/api/chat/resume'
    | '/api/rpc/$'
    | '/api/storage/$'
    | '/(auth)/two-factor/'
    | '/(dashboard)/chat/'
    | '/(dashboard)/organizations/'
    | '/(dashboard)/overview/'
    | '/(dashboard)/settings/'
    | '/api/chat/'
    | '/api/transcribe/'
    | '/(dashboard)/organizations/invitations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLayoutRoute: typeof authLayoutRouteWithChildren
  dashboardLayoutRoute: typeof dashboardLayoutRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ThemesRoute: typeof ThemesRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatResumeRoute: typeof ApiChatResumeRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiStorageSplatRoute: typeof ApiStorageSplatRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiTranscribeIndexRoute: typeof ApiTranscribeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsLayoutRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/api/transcribe/': {
      id: '/api/transcribe/'
      path: '/api/transcribe'
      fullPath: '/api/transcribe/'
      preLoaderRoute: typeof ApiTranscribeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/': {
      id: '/(dashboard)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof dashboardSettingsIndexRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/overview/': {
      id: '/(dashboard)/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof dashboardOverviewIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/organizations/': {
      id: '/(dashboard)/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof dashboardOrganizationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(dashboard)/chat/': {
      id: '/(dashboard)/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof dashboardChatIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
    '/(auth)/two-factor/': {
      id: '/(auth)/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof authTwoFactorIndexRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/api/storage/$': {
      id: '/api/storage/$'
      path: '/api/storage/$'
      fullPath: '/api/storage/$'
      preLoaderRoute: typeof ApiStorageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/resume': {
      id: '/api/chat/resume'
      path: '/api/chat/resume'
      fullPath: '/api/chat/resume'
      preLoaderRoute: typeof ApiChatResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings/security': {
      id: '/(dashboard)/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof dashboardSettingsSecurityRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/settings/billing': {
      id: '/(dashboard)/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof dashboardSettingsBillingRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(dashboard)/settings/appearance': {
      id: '/(dashboard)/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof dashboardSettingsAppearanceRouteImport
      parentRoute: typeof dashboardSettingsLayoutRoute
    }
    '/(auth)/two-factor/otp': {
      id: '/(auth)/two-factor/otp'
      path: '/two-factor/otp'
      fullPath: '/two-factor/otp'
      preLoaderRoute: typeof authTwoFactorOtpRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(auth)/accept-invitation/$invitationId': {
      id: '/(auth)/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof authAcceptInvitationInvitationIdRouteImport
      parentRoute: typeof authLayoutRoute
    }
    '/(dashboard)/organizations/invitations/': {
      id: '/(dashboard)/organizations/invitations/'
      path: '/organizations/invitations'
      fullPath: '/organizations/invitations/'
      preLoaderRoute: typeof dashboardOrganizationsInvitationsIndexRouteImport
      parentRoute: typeof dashboardLayoutRoute
    }
  }
}

interface authLayoutRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authAcceptInvitationInvitationIdRoute: typeof authAcceptInvitationInvitationIdRoute
  authTwoFactorOtpRoute: typeof authTwoFactorOtpRoute
  authTwoFactorIndexRoute: typeof authTwoFactorIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authAcceptInvitationInvitationIdRoute: authAcceptInvitationInvitationIdRoute,
  authTwoFactorOtpRoute: authTwoFactorOtpRoute,
  authTwoFactorIndexRoute: authTwoFactorIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface dashboardSettingsLayoutRouteChildren {
  dashboardSettingsAppearanceRoute: typeof dashboardSettingsAppearanceRoute
  dashboardSettingsBillingRoute: typeof dashboardSettingsBillingRoute
  dashboardSettingsSecurityRoute: typeof dashboardSettingsSecurityRoute
  dashboardSettingsIndexRoute: typeof dashboardSettingsIndexRoute
}

const dashboardSettingsLayoutRouteChildren: dashboardSettingsLayoutRouteChildren =
  {
    dashboardSettingsAppearanceRoute: dashboardSettingsAppearanceRoute,
    dashboardSettingsBillingRoute: dashboardSettingsBillingRoute,
    dashboardSettingsSecurityRoute: dashboardSettingsSecurityRoute,
    dashboardSettingsIndexRoute: dashboardSettingsIndexRoute,
  }

const dashboardSettingsLayoutRouteWithChildren =
  dashboardSettingsLayoutRoute._addFileChildren(
    dashboardSettingsLayoutRouteChildren,
  )

interface dashboardLayoutRouteChildren {
  dashboardSettingsLayoutRoute: typeof dashboardSettingsLayoutRouteWithChildren
  dashboardChatIndexRoute: typeof dashboardChatIndexRoute
  dashboardOrganizationsIndexRoute: typeof dashboardOrganizationsIndexRoute
  dashboardOverviewIndexRoute: typeof dashboardOverviewIndexRoute
  dashboardOrganizationsInvitationsIndexRoute: typeof dashboardOrganizationsInvitationsIndexRoute
}

const dashboardLayoutRouteChildren: dashboardLayoutRouteChildren = {
  dashboardSettingsLayoutRoute: dashboardSettingsLayoutRouteWithChildren,
  dashboardChatIndexRoute: dashboardChatIndexRoute,
  dashboardOrganizationsIndexRoute: dashboardOrganizationsIndexRoute,
  dashboardOverviewIndexRoute: dashboardOverviewIndexRoute,
  dashboardOrganizationsInvitationsIndexRoute:
    dashboardOrganizationsInvitationsIndexRoute,
}

const dashboardLayoutRouteWithChildren = dashboardLayoutRoute._addFileChildren(
  dashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLayoutRoute: authLayoutRouteWithChildren,
  dashboardLayoutRoute: dashboardLayoutRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ThemesRoute: ThemesRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatResumeRoute: ApiChatResumeRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiStorageSplatRoute: ApiStorageSplatRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiTranscribeIndexRoute: ApiTranscribeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
